services:
  bookingapp.db:
    container_name: bookingapp.db
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "BookingAppDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - bookingapp_db:/var/lib/posgresql
  
  bookingapp.migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    depends_on:
      - bookingapp.db
  
  bookingapp.api:
    container_name: bookingapp.api
    image: bookingapp.api
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      bookingapp.migrator:
        condition: service_completed_successfully
        
  bookingapp.ui:
    container_name: bookingapp.ui
    image: bookingapp.ui
    build:
      context: BookingApp.UI/
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    depends_on:
      bookingapp.api:
        condition: service_started

volumes:
  bookingapp_db: