@BaseUrl = {{Host}}/bookings
@BookingId = 409b4c5f-556c-44a8-867c-45aabf0ca83f
@MemberId = 29bdd5b4-a75f-4ce9-a35f-bf22d6006204
@RoomId = 585c8407-57fb-4886-ae7c-733191f65132

### Get Bookings by Member Id
GET {{BaseUrl}}?memberId={{MemberId}}
Accept: application/json
Authorization: Bearer {{Token}}

### Get Booking by Id
GET {{BaseUrl}}/{{BookingId}}
Accept: application/json
Authorization: Bearer {{Token}}

### Post new Booking
POST {{BaseUrl}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "attendeeCount": 1,
  "startTime": "2026-08-10T20:00:00Z",
  "endTime": "2026-08-11T19:35:00Z",
  "memberId": "{{MemberId}}",
  "roomId": "{{RoomId}}"
}

### Update new Booking
PUT {{BaseUrl}}/{{BookingId}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "attendeeCount": 2,
  "startTime": "2026-08-11T20:14:00Z",
  "endTime": "2026-08-12T19:35:00Z",
  "roomId": "{{RoomId}}"
}

### Delete Member
DELETE {{BaseUrl}}/{{BookingId}}
Authorization: Bearer {{Token}}