@BaseUrl = {{Host}}/members
@MemberId = 51f7b919-872d-406e-9ad1-e0b03c02296d

### Get all Members
GET {{BaseUrl}}
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNNS1ktTkV0aVZ2MEFXX1libkYtciJ9.eyJpc3MiOiJodHRwczovL2Rldi1jcm4uZXUuYXV0aDAuY29tLyIsInN1YiI6Ikh4V0ZGZFdnOG4xQVZLT05qSGFPZW1MYThyRVU0MHNyQGNsaWVudHMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJpYXQiOjE3ODYwMzIzNjMsImV4cCI6MTc4NjExODc2MywiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiSHhXRkZkV2c4bjFBVktPTmpIYU9lbUxhOHJFVTQwc3IifQ.q0wz8Vjp4-KdL728JKLFyDebVqJqPsvQx4mZFdoiaIRs0gj-8-u9HIqgkkndhspD7EW4hR0uGYq5wGujekm8m4Hd6fG82BPWCgWpP4TH7krttHPRGkGUZGZIVbXU00_Moi_PLzkPwMEIHudyUVEZhwpP4cCgafWiZjpaM_M9CbKRC7o0hh7TbIRCrsVn9lX_p1B6oyacY_qquE0y7Uml0AAv2IvrBs2Rys0dZ06GQhb2s8MBUSkno2a8KM0b6SPeV0Ofd7xl7HhGPCCiiegr4o71vgF5BSeskb1XPERq9J2TfBgDJ_ZdXAOtAz0I6L7ndUZeEzPYXmF0JxLO7KWuKg

### Get Member by Id
GET {{BaseUrl}}/{{MemberId}}
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNNS1ktTkV0aVZ2MEFXX1libkYtciJ9.eyJpc3MiOiJodHRwczovL2Rldi1jcm4uZXUuYXV0aDAuY29tLyIsInN1YiI6Ikh4V0ZGZFdnOG4xQVZLT05qSGFPZW1MYThyRVU0MHNyQGNsaWVudHMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJpYXQiOjE3ODYwMzIzNjMsImV4cCI6MTc4NjExODc2MywiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiSHhXRkZkV2c4bjFBVktPTmpIYU9lbUxhOHJFVTQwc3IifQ.q0wz8Vjp4-KdL728JKLFyDebVqJqPsvQx4mZFdoiaIRs0gj-8-u9HIqgkkndhspD7EW4hR0uGYq5wGujekm8m4Hd6fG82BPWCgWpP4TH7krttHPRGkGUZGZIVbXU00_Moi_PLzkPwMEIHudyUVEZhwpP4cCgafWiZjpaM_M9CbKRC7o0hh7TbIRCrsVn9lX_p1B6oyacY_qquE0y7Uml0AAv2IvrBs2Rys0dZ06GQhb2s8MBUSkno2a8KM0b6SPeV0Ofd7xl7HhGPCCiiegr4o71vgF5BSeskb1XPERq9J2TfBgDJ_ZdXAOtAz0I6L7ndUZeEzPYXmF0JxLO7KWuKg

### Post new Member
POST {{BaseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNNS1ktTkV0aVZ2MEFXX1libkYtciJ9.eyJpc3MiOiJodHRwczovL2Rldi1jcm4uZXUuYXV0aDAuY29tLyIsInN1YiI6Ikh4V0ZGZFdnOG4xQVZLT05qSGFPZW1MYThyRVU0MHNyQGNsaWVudHMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJpYXQiOjE3ODYwMzIzNjMsImV4cCI6MTc4NjExODc2MywiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiSHhXRkZkV2c4bjFBVktPTmpIYU9lbUxhOHJFVTQwc3IifQ.q0wz8Vjp4-KdL728JKLFyDebVqJqPsvQx4mZFdoiaIRs0gj-8-u9HIqgkkndhspD7EW4hR0uGYq5wGujekm8m4Hd6fG82BPWCgWpP4TH7krttHPRGkGUZGZIVbXU00_Moi_PLzkPwMEIHudyUVEZhwpP4cCgafWiZjpaM_M9CbKRC7o0hh7TbIRCrsVn9lX_p1B6oyacY_qquE0y7Uml0AAv2IvrBs2Rys0dZ06GQhb2s8MBUSkno2a8KM0b6SPeV0Ofd7xl7HhGPCCiiegr4o71vgF5BSeskb1XPERq9J2TfBgDJ_ZdXAOtAz0I6L7ndUZeEzPYXmF0JxLO7KWuKg

{
  "firstName": "Dean",
  "lastName": "Winchester",
  "role": "Customer",
  "email": "d.winchester@gmail.com",
  "phoneNumber": "+11234567890"
}

### Update Member
PUT {{BaseUrl}}/{{MemberId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNNS1ktTkV0aVZ2MEFXX1libkYtciJ9.eyJpc3MiOiJodHRwczovL2Rldi1jcm4uZXUuYXV0aDAuY29tLyIsInN1YiI6Ikh4V0ZGZFdnOG4xQVZLT05qSGFPZW1MYThyRVU0MHNyQGNsaWVudHMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJpYXQiOjE3ODYwMzIzNjMsImV4cCI6MTc4NjExODc2MywiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiSHhXRkZkV2c4bjFBVktPTmpIYU9lbUxhOHJFVTQwc3IifQ.q0wz8Vjp4-KdL728JKLFyDebVqJqPsvQx4mZFdoiaIRs0gj-8-u9HIqgkkndhspD7EW4hR0uGYq5wGujekm8m4Hd6fG82BPWCgWpP4TH7krttHPRGkGUZGZIVbXU00_Moi_PLzkPwMEIHudyUVEZhwpP4cCgafWiZjpaM_M9CbKRC7o0hh7TbIRCrsVn9lX_p1B6oyacY_qquE0y7Uml0AAv2IvrBs2Rys0dZ06GQhb2s8MBUSkno2a8KM0b6SPeV0Ofd7xl7HhGPCCiiegr4o71vgF5BSeskb1XPERq9J2TfBgDJ_ZdXAOtAz0I6L7ndUZeEzPYXmF0JxLO7KWuKg

{
  "firstName": "Dean",
  "lastName": "Winchester",
  "email": "d.winchester@gmail.com",
  "phoneNumber": "+11234567890"
}

### Delete Member
DELETE {{BaseUrl}}/{{MemberId}}
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNNS1ktTkV0aVZ2MEFXX1libkYtciJ9.eyJpc3MiOiJodHRwczovL2Rldi1jcm4uZXUuYXV0aDAuY29tLyIsInN1YiI6Ikh4V0ZGZFdnOG4xQVZLT05qSGFPZW1MYThyRVU0MHNyQGNsaWVudHMiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJpYXQiOjE3ODYwMzIzNjMsImV4cCI6MTc4NjExODc2MywiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiSHhXRkZkV2c4bjFBVktPTmpIYU9lbUxhOHJFVTQwc3IifQ.q0wz8Vjp4-KdL728JKLFyDebVqJqPsvQx4mZFdoiaIRs0gj-8-u9HIqgkkndhspD7EW4hR0uGYq5wGujekm8m4Hd6fG82BPWCgWpP4TH7krttHPRGkGUZGZIVbXU00_Moi_PLzkPwMEIHudyUVEZhwpP4cCgafWiZjpaM_M9CbKRC7o0hh7TbIRCrsVn9lX_p1B6oyacY_qquE0y7Uml0AAv2IvrBs2Rys0dZ06GQhb2s8MBUSkno2a8KM0b6SPeV0Ofd7xl7HhGPCCiiegr4o71vgF5BSeskb1XPERq9J2TfBgDJ_ZdXAOtAz0I6L7ndUZeEzPYXmF0JxLO7KWuKg
