@BaseUrl = {{Host}}/members
@MemberId = 29bdd5b4-a75f-4ce9-a35f-bf22d6006204

### Get all Members
GET {{BaseUrl}}
Accept: application/json
Authorization: Bearer {{Token}}

### Get Member by Id
GET {{BaseUrl}}/{{MemberId}}
Accept: application/json
Authorization: Bearer {{Token}}

### Post new Member
POST {{BaseUrl}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "firstName": "Dean",
  "lastName": "Winchester",
  "role": "Customer",
  "email": "d.winchester@gmail.com",
  "phoneNumber": "+11234567890"
}

### Update Member
PUT {{BaseUrl}}/{{MemberId}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "firstName": "Sam",
  "lastName": "Winchester",
  "email": "s.winchester@gmail.com",
  "phoneNumber": "+11234567890"
}

### Delete Member
DELETE {{BaseUrl}}/{{MemberId}}
Authorization: Bearer {{Token}}
